theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-o = ":open ~/.config/helix/config.toml"
C-r = ":config-reload"
C-g = ":sh tmux send-keys -t 2 lazygit Enter && tmux select-pane -t 2"
C-n = ":n"

[keys.insert]
C-s = ":w"

[keys.normal.space]
q = ":q"
