theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-f = [":new", ":insert-output lf-pick", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":theme onedark", ":theme default" ]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% lazygit"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-n = ":n"
C-o = ":config-open"
C-r = ":config-reload"
C-t = ":sh tmux popup -d \"#{pane_current_path}\" "
C-x = ":o ~/.config/helix/languages.toml"

[keys.insert]
C-s = ["normal_mode", ":w"]

[keys.normal.space]
q = ":q"
x = ":bc"
";" = ":w"
v = ":sh hemux-last"
"'" = ":q!"
l = ":log-open"

[editor.lsp]
display-messages = true
display-inlay-hints = true
