env:
  TERM: alacritty
  LANG: en_US.UTF-8
  LC_CTYPE: en_US.UTF-8

font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  bold:
    family: Hack Nerd Font Mono
    style: Bold

  italic:
    family: Hack Nerd Font Mono
    style: Italic

  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  size: 12
colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  # Normal colors
  normal:
    black: '#000000'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#caa9fa'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#bfbfbf'

  # Bright colors
  bright:
    black: '#575b70'
    red: '#ff6e67'
    green: '#5af78e'
    yellow: '#f4f99d'
    blue: '#caa9fa'
    magenta: '#ff92d0'
    cyan: '#9aedfe'
    white: '#e6e6e6'
